---

- name: localhost configuration
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: ensure aptitude is installed
    command: apt-get -y install aptitude
  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes

  - name: install other dependencies
    command: apt-get -y install git

  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest
