---
# tasks file for server
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600
    become: yes

  - name: Install required software
    apt: 
      name: ['apache2', 'php', 'php-mysql']
      state: present
    become: yes

# tasks file for php
  - name: Install php extensions
    apt: 
      name: ['php-gd', 'php-ssh2']
      state: present
    become: yes

  - name: Install other dependencies
    apt:
      name: ['unzip']
      state: present
    become: yes

# wordpress install
  - name: Download WordPress
    get_url: 
      url=https://wordpress.org/latest.tar.gz 
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

  - name: Extract WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
    become: yes

  - name: Update default Apache site
    become: yes
    lineinfile: 
      dest=/etc/apache2/sites-enabled/000-default.conf 
      regexp="(.)+DocumentRoot /var/www/html"
      line="DocumentRoot /var/www/wordpress"
    notify:
      - restart apache

  - name: Copy sample config file
    command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
    become: yes

#  - name: delete db username in wp-config.php
#    replace:
#      path: "{{wp_dir}}/wordpress/wp-config.php"
#      regexp: "(.*)username_here(.*)"
#
#  - name: delete db password in wp-config.php
#    replace:
#      path: "{{wp_dir}}/wordpress/wp-config.php"
#      regexp: "(.*)password_here(.*)"
#
#  - name: delete db name in wp-config.php
#    replace:
#      path: "{{wp_dir}}/wordpress/wp-config.php"
#      regexp: "(.*)database_name_here(.*)"
# 
#  - name: delete db host in wp-config.php
#    replace:
#      path: "{{wp_dir}}/wordpress/wp-config.php"
#      regexp: "(.*)localhost(.*)"
#
#  - name: delete lines in wp-config.php
#    replace:
#      path: "{{wp_dir}}/wordpress/wp-config.php"
#      regexp: "(.*)put your unique phrase here(.*)"

  - name: clear wp-config.php
    replace:
      path: "{{wp_dir}}/wordpress/wp-config.php"
      regexp: ".*"

  - name: add php header to blank wp-config.php
    copy:
      content: "<?php"
      dest: "{{wp_dir}}/wordpress/wp-config.php"

  - name: Append db config to wp-config.php
    blockinfile:
      path: "{{wp_dir}}/wordpress/wp-config.php"
      marker: "# {mark} ANSIBLEMANAGED BLOCK: DB-Config"
      block: |
        define( 'DB_NAME', '{{ wp_db_name }}' );
        define( 'DB_USER', '{{ wp_db_user }}' );
        define( 'DB_PASSWORD', '{{ wp_db_password }}' );
        define( 'DB_HOST', '{{ wp_db_host }}' );
        define( 'DB_CHARSET', 'utf8' );
        define( 'DB_COLLATE', '' );
        $table_prefix = 'wp_';
      insertafter: "EOF"

  - name: Download salt file
    get_url:
      url: https://api.wordpress.org/secret-key/1.1/salt
      dest: "{{wp_dir}}/salt.txt"

  - name: Get contents of salt file
    slurp:
      src: "{{wp_dir}}/salt.txt"
    register: salts_content

  - name: Append salt file content to wp-config.php
    blockinfile:
      path: "{{wp_dir}}/wordpress/wp-config.php"
      marker: "# {mark} ANSIBLEMANAGED BLOCK: SALT"
      block: "{{ salts_content['content'] | b64decode }}"
      insertafter: "EOF"

  - name: Add required footer to wp-config.php
    blockinfile:
      path: "{{wp_dir}}/wordpress/wp-config.php"
      marker: "# {mark} ANSIBLEMANAGED BLOCK: Footer"
      block: |
        define( 'WP_DEBUG', false );
        if ( ! defined( 'ABSPATH' ) ) {
          define( 'ABSPATH', dirname( __FILE__ ) . '/' );
        }
        require_once( ABSPATH . 'wp-settings.php' );
      insertafter: "EOF"

  - name: download plugin(s)
    get_url:
      url: "https://downloads.wordpress.org/plugin/{{ item }}.zip"
      dest: "/tmp/{{ item }}.zip"
      force: no
    with_items:
      - wp-stateless
      - fakerpress

  - name: extract plugin(s)
    unarchive:
      src: "/tmp/{{ item }}.zip"
      dest: "{{wp_dir}}/wordpress/wp-content/plugins"
      creates: "{{wp_dir}}/wordpress/wp-content/plugins/{{ item }}/"
      copy: false
    with_items:
      - wp-stateless
      - fakerpress

  - name: change permissions for /var/www
    file:
      path: "{{ wp_dir }}"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

